In [ ]:
# NAIVE BAYES

# 1.MULTINOMIAL NAIVE BAYES

In [ ]:
import pandas as pd
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import LabelEncoder

In [ ]:
df=pd.read_csv("real_drug_dataset.csv")
df

,Patient_ID,Age,Gender,Condition,Drug_Name,Dosage_mg,Treatment_Duration_days,Side_Effects,Improvement_Score
0,P0001,56,Male,Infection,Ciprofloxacin,50,9,Nausea,8.5
1,P0002,69,Male,Hypertension,Metoprolol,500,24,Tiredness,8.7
2,P0003,46,Female,Depression,Bupropion,100,25,Dry mouth,5.4
3,P0004,32,Male,Diabetes,Glipizide,850,44,Low blood sugar,6.4
4,P0005,60,Male,Depression,Bupropion,850,35,Anxiety,5.3
...,...,...,...,...,...,...,...,...,...
995,P0996,18,Male,Hypertension,Losartan,100,44,Headache,7.7
996,P0997,35,Female,Infection,Azithromycin,50,15,Nausea,5.3
997,P0998,49,Female,Depression,Sertraline,850,52,Dry mouth,8.0
998,P0999,64,Male,Depression,Escitalopram,850,36,Nausea,7.6
999,P1000,66,Female,Hypertension,Metoprolol,500,58,Tiredness,6.5

In [ ]:
df.isnull().sum()

Patient_ID                 0
Age                        0
Gender                     0
Condition                  0
Drug_Name                  0
Dosage_mg                  0
Treatment_Duration_days    0
Side_Effects               0
Improvement_Score          0
dtype: int64

In [ ]:
le=LabelEncoder()

In [ ]:
df["Condition"]=le.fit_transform(df["Condition"])
df["Condition"]

0      3
1      2
2      0
3      1
4      0
      ..
995    2
996    3
997    0
998    0
999    2
Name: Condition, Length: 1000, dtype: int64

In [ ]:
df["Drug_Name"]=le.fit_transform(df["Drug_Name"])
df["Drug_Name"]

0       4
1      11
2       3
3       6
4       3
       ..
995     9
996     2
997    13
998     5
999    11
Name: Drug_Name, Length: 1000, dtype: int64

In [ ]:
x=df [["Age","Condition","Drug_Name","Dosage_mg"]]

In [ ]:
y=le.fit_transform(df["Side_Effects"])
y

array([19, 28,  9, 17,  2,  7, 19, 16, 19, 19, 11, 19,  7,  9, 19,  7,  0,
       17,  9, 19,  2, 18, 16,  3, 19,  7, 28, 19, 21, 28,  7, 29, 16, 17,
       14, 17, 17, 11, 19,  6, 29, 26, 14,  4,  1, 10, 20, 11,  4, 27, 16,
        7, 17,  7, 19,  0,  7,  5,  9, 19, 29,  7, 17, 20,  7, 10, 15, 28,
       27, 10,  7, 10, 26, 19, 15, 15,  6, 11, 20,  2, 19, 25,  3,  4,  4,
        2, 19, 15, 19,  9, 19, 29,  8, 13, 10,  6, 10, 11, 21,  2,  1,  6,
       10,  5,  9, 19, 18,  3, 20,  2, 13, 11, 21, 25,  7, 22, 22, 11, 11,
       10,  3, 19, 11, 18,  8,  5, 22, 22,  7,  6,  7, 14,  7, 19, 19, 29,
       27,  7, 19, 14, 26, 29, 10,  8, 19, 25, 17, 15,  4,  7,  4,  6, 19,
       27, 17, 19, 20, 14, 29, 11, 17,  9, 20, 11,  7, 14, 24,  7,  8, 14,
        5, 15,  9,  6, 11, 11, 21, 16, 26, 24,  1,  2,  0, 19,  7,  8, 29,
       29,  9, 11, 25,  4, 13,  6,  0, 19, 21, 19, 19,  7, 11,  7, 13, 24,
        1, 26,  2, 17,  7, 13,  4, 19,  6, 19, 19,  7,  4, 19,  7, 19, 28,
        4, 27, 18,  5, 25, 19,  6, 13, 19, 16, 19,  2, 22, 10, 11, 24, 19,
        8,  3, 11,  2,  6, 18, 17, 13,  0, 19, 23, 14,  7, 10, 19, 15,  9,
       24, 21,  4,  9, 22,  9,  7, 19, 19, 11, 19, 15, 19,  4, 14,  3,  7,
        2, 26, 11, 29, 20, 21, 11,  2,  5, 11, 19, 25, 12, 26, 24,  3, 11,
        1,  1, 11, 25, 19, 22, 20, 16, 11, 24, 13, 11, 10,  7,  7, 16, 12,
        7,  7,  3, 24,  1, 19, 25, 26,  6,  7, 19, 17,  6,  2, 19,  5, 23,
       19,  7, 11, 14,  7,  3, 24, 28, 20, 19, 10, 13, 25, 19, 27, 17,  5,
       11, 10,  7, 11, 20, 10, 21, 13, 19, 13, 18, 21, 21,  7, 23, 11,  1,
       26, 14,  7, 11, 11, 19, 20,  6, 24, 19, 22,  8, 19, 24, 17, 29,  9,
       28, 12, 29,  8, 21, 19, 20,  0, 10, 15,  8, 13, 14, 16, 19,  0,  1,
        2, 12, 19, 18, 11, 19,  7,  8,  2,  4, 25, 11, 19, 15, 11, 28, 24,
        5, 15, 19, 20, 19,  1, 19,  4, 16, 10, 16, 19,  3, 22, 28, 10, 19,
        7, 19, 20, 13, 29, 24,  6, 19, 26, 17,  7, 20, 26,  0, 21,  6, 11,
       26, 29, 19, 18,  4, 29,  1, 20,  7, 11, 10, 11, 27, 19, 29, 10, 22,
        5, 27,  7, 19, 19,  1, 20,  7, 19, 20, 19, 26, 25,  2, 25, 19,  6,
       20, 28,  5, 19, 19, 22, 12, 28,  3,  4, 24, 28, 19,  1,  7, 24,  7,
       10, 27, 24, 19,  7,  9, 20, 19, 18, 29,  3, 15, 20, 19, 20, 11,  9,
        0,  0,  9, 19,  3,  5, 22,  7, 18, 10, 19, 13,  2,  9, 19, 11,  6,
       20,  3, 22, 21, 12, 12, 20, 19, 25, 13, 10, 18,  6, 11, 15,  6, 25,
        7, 25,  9, 19, 13,  6,  7, 18, 28, 20, 11, 10, 19,  5,  7, 11, 19,
       20, 11, 18, 16, 19, 25, 28, 11, 28, 27, 15, 28, 19,  7,  3,  9, 16,
       25,  1,  4,  8, 18, 18, 15,  7, 22, 19,  9, 10, 27, 11,  3, 24,  6,
       11, 14, 19, 19,  3, 10, 23,  5, 22, 10, 13, 11,  9, 13, 25, 10,  8,
       20, 19, 19, 20, 19,  1, 19,  5,  7,  6, 13, 19, 24, 16, 11, 18, 20,
       19,  8,  1, 19,  9, 19, 10, 28,  4,  2, 22,  7, 11,  6, 14, 21, 20,
        7,  0, 24,  9, 19,  7, 14, 19,  4, 18, 17, 23, 11, 16,  6, 23,  8,
       20, 17,  7, 27, 17, 19, 29, 20,  7, 19,  3, 10, 11, 13, 14, 20,  7,
       12, 27, 19,  7, 18, 18, 11,  7, 17, 23, 17,  2, 11, 16, 13, 19, 24,
       19, 21, 11,  6, 19, 12, 19,  7, 29,  0,  7,  9, 19, 25, 27,  1, 11,
       19, 22, 24, 22, 19,  7, 19, 19,  7, 23, 13, 14,  6, 13, 22, 19,  1,
       27,  3, 19, 24,  2, 20, 17,  6, 15, 19,  1, 23, 24,  2, 11, 11, 11,
        7, 16,  7,  3, 16, 29, 19, 20, 10, 11, 11, 25, 11, 20, 19,  6, 11,
       18, 12, 19,  7,  9, 21,  4, 20, 21, 19, 11,  7,  7,  7,  6, 10,  7,
       27, 12, 24, 11, 15, 19,  9,  6, 12, 12, 27, 23,  7, 19, 19, 23, 11,
       16, 19, 29, 19,  7,  7, 19, 19, 19, 10,  1, 19, 26,  7, 23, 10, 19,
       26,  7,  6, 12, 17,  8,  9, 12, 19, 10, 21, 10,  3,  6, 19, 11, 11,
       18, 14, 19,  7,  1, 14, 29,  8, 17, 19, 19, 24, 18, 13,  5, 18, 10,
       19,  7,  4,  7,  6,  7,  2,  8, 28,  5, 20, 19, 19, 11, 17, 19, 10,
       20, 11, 24, 16, 20, 19, 19, 19, 15, 19, 11, 14, 29, 19, 11, 22,  6,
        2, 17, 17, 10, 19,  8, 19,  7, 10,  9, 10,  9, 19,  7, 24,  8,  7,
        7, 19, 12,  7, 11, 24,  7,  0, 10, 20, 19, 25, 20,  4, 15,  9, 19,
       20, 15,  7, 19, 18, 11, 15, 11, 13, 29,  7, 10, 19,  7, 18, 29,  7,
       15, 19, 19, 20,  7, 19, 10, 19,  3, 12, 26, 15, 24, 11, 18, 12,  6,
       20, 19, 21,  2, 23, 19, 10, 20, 18, 19, 19,  6, 28,  3, 10,  7,  7,
        3, 25,  7,  7, 27, 19, 25, 19,  4,  1, 12, 14, 29, 22, 23,  3, 10,
        1, 14,  7,  4, 10, 20, 19, 11,  8, 11, 19,  9, 19, 28])

In [ ]:
models=MultinomialNB()
models.fit(x,y)

MultinomialNB()

In [ ]:
test=pd.DataFrame({"Age":[45],"Condition":[1],"Drug_Name":[5],"Dosage_mg":[100]})

In [ ]:
pred=models.predict(test)
pred

array([25])

In [ ]:
print("Predicted side effects:",le.inverse_transform(pred)[0])

Predicted side effects: Stomach upset

In [ ]:
# 2.GAUSSIAN NAIVE BAYES

In [ ]:
import pandas as pd
from sklearn.naive_bayes import GaussianNB

In [ ]:
data=pd.read_csv("IRIS.csv")
data

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
data.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [ ]:
data["species"].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
x=data[["sepal_length","sepal_width","petal_length","petal_width"]]
y=data[["species"]]

In [ ]:
i_model=GaussianNB()

In [ ]:
i_model.fit(X_train,Y_train)

GaussianNB()

In [ ]:
y_pred=i_model.predict(X_test)
y_pred

array([29, 17,  4, 25,  1,  1,  2,  0,  3, 27, 22,  1, 28, 27,  1, 14,  3,
        1, 16,  2, 25,  3, 17,  1,  4,  0,  1,  1,  4, 24, 17, 14,  1,  1,
       12, 26, 15, 15, 27, 15,  3, 27, 25, 25, 18, 17, 15, 23, 17,  1, 27,
       18, 27, 25,  3, 15,  1,  2,  4, 17, 16, 12,  1, 29, 16,  0, 14, 27,
        4, 25,  3, 27, 27,  1, 25,  1, 14,  1, 27, 27, 15, 15, 13, 28, 25,
       18, 22, 15, 18, 28, 27,  5,  2,  4, 24, 16,  2, 15,  1, 17, 24, 17,
        0, 17, 16, 17,  2,  1, 14, 22,  3, 24, 16, 26,  4, 22, 23,  1,  4,
       22, 27, 15,  3,  2,  0,  2, 13, 29, 16, 12,  3, 27, 15,  5, 26,  0,
        3,  4, 15, 26,  1,  4, 15,  3, 14,  4, 17, 17,  2,  3,  8, 18,  4,
       18, 27, 17, 24, 24, 18,  2,  0, 25,  2, 15,  4,  0, 24, 28,  1,  1,
        3,  0, 18,  4, 12, 16,  8, 26,  0, 14, 27, 16, 14, 25, 13, 27,  2,
       12, 26, 16,  0, 25, 17, 27,  0,  3, 24, 28, 25, 16])

In [ ]:
Y_test

array([13, 17, 19,  6, 20, 20, 11, 19,  5, 27, 26,  6, 28, 27, 20,  8,  5,
        6, 20,  2,  6, 11, 17, 20,  4, 11,  6,  1, 19, 24, 21, 14,  6, 20,
       24, 19,  7, 15,  7, 19,  3, 10, 25, 19, 13, 21, 15, 23, 21,  1, 27,
       29,  7, 25,  3,  7,  1, 11,  4, 17, 16, 19,  6, 13, 10, 11,  8, 10,
        7, 25,  3, 10, 27,  1, 25,  1, 14,  6, 10,  7,  7, 15, 29, 28,  6,
       13, 19, 19, 29,  7, 10, 11,  2,  7, 19, 20, 11, 19, 20, 21, 24, 21,
       19, 21, 10, 21, 11, 20,  8, 19,  3, 12, 10, 26, 19, 19,  7,  1, 19,
       22, 10,  7, 11,  9, 19, 11, 18, 18, 20, 19,  3, 10, 19, 11, 22,  0,
        3,  7,  7, 26,  1, 19, 19, 11,  9,  4, 19, 17,  9,  5, 14, 29,  4,
       29, 10, 19, 24, 19, 29,  2, 11, 19,  9, 19, 19, 19, 24, 23,  6,  1,
       11, 19, 13,  4, 24, 20,  9, 22, 19, 14, 27, 20,  8,  6, 18,  7, 11,
       24, 19, 16, 11,  6, 17,  7, 19,  5, 19,  7, 19, 20])

In [63]:
new_flower=[[5.1,3.5,1.4,0.2]]
prediction=i_model.predict(new_flower)
prediction
print("predicted new flower species:",prediction)

predicted new flower species: [20]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(

In [64]:
new_flower1=[[6.7,3.0,5.2,2.3]]
prediction1=i_model.predict(new_flower1)
prediction1
print("predicted new flower species:",prediction1)

predicted new flower species: [19]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(

In [ ]:
# 3.BERNOULLI NAIVE BAYES

In [ ]:
import numpy as np
from sklearn.naive_bayes import BernoulliNB

In [ ]:
ds=pd.read_csv("rainfall.csv")
ds

          date  rainfall  temperature  humidity  wind_speed weather_condition
0   2022-01-01      12.5         15.2      78.0         8.5             Rainy
1   2022-01-02       8.2         17.8      65.0         5.2             Rainy
2   2022-01-03       0.0         20.1      52.0         3.1             Sunny
3   2022-01-04       3.7         18.6      71.0         6.7             Rainy
4   2022-01-05      21.1         14.8      82.0         9.3             Rainy
5   2022-01-06      15.3         16.5      75.0         7.8             Rainy
6   2022-01-07       6.8         19.2      61.0         4.5             Rainy
7   2022-01-08       0.0         21.7      48.0         2.9             Sunny
8   2022-01-09      11.2         17.3      73.0         6.1             Rainy
9   2022-01-10      18.6         15.8      79.0         8.9             Rainy
10  2022-01-11       9.5         16.2      72.0         5.7             Rainy
11  2022-01-12       2.1         19.8      58.0         3.5             Rainy
12  2022-01-13       0.0         22.4      45.0         2.1             Sunny
13  2022-01-14       7.4         17.9      69.0         6.5             Rainy
14  2022-01-15      14.9         15.1      81.0         8.7             Rainy
15  2022-01-16      19.2         16.8      77.0         7.2             Rainy
16  2022-01-17       5.6         18.5      63.0         4.9             Rainy
17  2022-01-18       0.0         21.2      51.0         3.3             Sunny
18  2022-01-19      10.8         17.6      75.0         6.7             Rainy
19  2022-01-20      16.3         14.5      84.0         9.1             Rainy
20  2022-01-21       3.9         16.1      71.0         5.3             Rainy
21  2022-01-22       0.0         19.4      59.0         4.1             Sunny
22  2022-01-23       7.1         18.2      67.0         7.1             Rainy
23  2022-01-24      12.7         15.7      79.0         8.3             Rainy
24  2022-01-25      18.4         17.1      76.0         6.8             Rainy
25  2022-01-26       9.8         19.7      62.0         4.7             Rainy
26  2022-01-27       0.0         22.9      47.0         2.5             Sunny
27  2022-01-28       6.2         18.5      70.0         7.3             Rainy
28  2022-01-29      15.5         14.2      83.0         9.5             Rainy
29  2022-01-30      21.8         16.4      78.0         7.6             Rainy
30  2022-01-31      11.6         19.1      65.0         5.1             Rainy
31  2022-02-01       0.0         21.6      53.0         3.7             Sunny
32  2022-02-02       4.3         17.2      73.0         7.5             Rainy
33  2022-02-03       9.1         15.4      81.0         8.9             Rainy
34  2022-02-04      17.9         16.7      77.0         6.2             Rainy
35  2022-02-05       7.5         18.9      64.0         4.3             Rainy
36  2022-02-06       0.0         22.1      49.0         2.7             Sunny
37  2022-02-07       5.8         17.8      72.0         6.9             Rainy
38  2022-02-08      13.2         14.7      85.0         9.3             Rainy
39  2022-02-09      19.6         16.2      79.0         7.8             Rainy
40  2022-02-10      10.4         19.5      66.0         5.5             Rainy
41  2022-02-11       0.0         23.4      44.0         3.1             Sunny
42  2022-02-12       6.7         18.1      74.0         7.7             Rainy
43  2022-02-13      14.8         13.9      87.0         9.9             Rainy
44  2022-02-14      20.5         15.6      81.0         8.2             Rainy
45  2022-02-15       8.3         19.2      68.0         6.1             Rainy
46  2022-02-16       0.0         22.7      51.0         4.5             Sunny
47  2022-02-17       5.1         17.4      75.0         8.3             Rainy
48  2022-02-18      11.9         14.1      89.0        10.5             Rainy
49  2022-02-19      17.3         15.9      83.0         8.6             Rainy
50  2022-02-20       9.6         18.6      71.0         6.7             Rainy
51  2022-02-21       0.0         21.3      55.0         5.1             Sunny
52  2022-02-22       7.4         16.8      77.0         8.9             Rainy
53          Co       NaN          NaN       NaN         NaN               NaN

In [ ]:
ds.isnull().sum()

date                 0
rainfall             1
temperature          1
humidity             1
wind_speed           1
weather_condition    1
dtype: int64

In [ ]:
ds=ds.drop(53)
ds

          date  rainfall  temperature  humidity  wind_speed weather_condition
0   2022-01-01      12.5         15.2      78.0         8.5             Rainy
1   2022-01-02       8.2         17.8      65.0         5.2             Rainy
2   2022-01-03       0.0         20.1      52.0         3.1             Sunny
3   2022-01-04       3.7         18.6      71.0         6.7             Rainy
4   2022-01-05      21.1         14.8      82.0         9.3             Rainy
5   2022-01-06      15.3         16.5      75.0         7.8             Rainy
6   2022-01-07       6.8         19.2      61.0         4.5             Rainy
7   2022-01-08       0.0         21.7      48.0         2.9             Sunny
8   2022-01-09      11.2         17.3      73.0         6.1             Rainy
9   2022-01-10      18.6         15.8      79.0         8.9             Rainy
10  2022-01-11       9.5         16.2      72.0         5.7             Rainy
11  2022-01-12       2.1         19.8      58.0         3.5             Rainy
12  2022-01-13       0.0         22.4      45.0         2.1             Sunny
13  2022-01-14       7.4         17.9      69.0         6.5             Rainy
14  2022-01-15      14.9         15.1      81.0         8.7             Rainy
15  2022-01-16      19.2         16.8      77.0         7.2             Rainy
16  2022-01-17       5.6         18.5      63.0         4.9             Rainy
17  2022-01-18       0.0         21.2      51.0         3.3             Sunny
18  2022-01-19      10.8         17.6      75.0         6.7             Rainy
19  2022-01-20      16.3         14.5      84.0         9.1             Rainy
20  2022-01-21       3.9         16.1      71.0         5.3             Rainy
21  2022-01-22       0.0         19.4      59.0         4.1             Sunny
22  2022-01-23       7.1         18.2      67.0         7.1             Rainy
23  2022-01-24      12.7         15.7      79.0         8.3             Rainy
24  2022-01-25      18.4         17.1      76.0         6.8             Rainy
25  2022-01-26       9.8         19.7      62.0         4.7             Rainy
26  2022-01-27       0.0         22.9      47.0         2.5             Sunny
27  2022-01-28       6.2         18.5      70.0         7.3             Rainy
28  2022-01-29      15.5         14.2      83.0         9.5             Rainy
29  2022-01-30      21.8         16.4      78.0         7.6             Rainy
30  2022-01-31      11.6         19.1      65.0         5.1             Rainy
31  2022-02-01       0.0         21.6      53.0         3.7             Sunny
32  2022-02-02       4.3         17.2      73.0         7.5             Rainy
33  2022-02-03       9.1         15.4      81.0         8.9             Rainy
34  2022-02-04      17.9         16.7      77.0         6.2             Rainy
35  2022-02-05       7.5         18.9      64.0         4.3             Rainy
36  2022-02-06       0.0         22.1      49.0         2.7             Sunny
37  2022-02-07       5.8         17.8      72.0         6.9             Rainy
38  2022-02-08      13.2         14.7      85.0         9.3             Rainy
39  2022-02-09      19.6         16.2      79.0         7.8             Rainy
40  2022-02-10      10.4         19.5      66.0         5.5             Rainy
41  2022-02-11       0.0         23.4      44.0         3.1             Sunny
42  2022-02-12       6.7         18.1      74.0         7.7             Rainy
43  2022-02-13      14.8         13.9      87.0         9.9             Rainy
44  2022-02-14      20.5         15.6      81.0         8.2             Rainy
45  2022-02-15       8.3         19.2      68.0         6.1             Rainy
46  2022-02-16       0.0         22.7      51.0         4.5             Sunny
47  2022-02-17       5.1         17.4      75.0         8.3             Rainy
48  2022-02-18      11.9         14.1      89.0        10.5             Rainy
49  2022-02-19      17.3         15.9      83.0         8.6             Rainy
50  2022-02-20       9.6         18.6      71.0         6.7             Rainy
51  2022-02-21       0.0         21.3      55.0         5.1             Sunny
52  2022-02-22       7.4         16.8      77.0         8.9             Rainy

In [ ]:
ds.isnull().sum()

date                 0
rainfall             0
temperature          0
humidity             0
wind_speed           0
weather_condition    0
dtype: int64

In [55]:
ds=ds.drop("date",axis=1)
ds

    rainfall  temperature  humidity  wind_speed weather_condition
0       12.5         15.2      78.0         8.5             Rainy
1        8.2         17.8      65.0         5.2             Rainy
2        0.0         20.1      52.0         3.1             Sunny
3        3.7         18.6      71.0         6.7             Rainy
4       21.1         14.8      82.0         9.3             Rainy
5       15.3         16.5      75.0         7.8             Rainy
6        6.8         19.2      61.0         4.5             Rainy
7        0.0         21.7      48.0         2.9             Sunny
8       11.2         17.3      73.0         6.1             Rainy
9       18.6         15.8      79.0         8.9             Rainy
10       9.5         16.2      72.0         5.7             Rainy
11       2.1         19.8      58.0         3.5             Rainy
12       0.0         22.4      45.0         2.1             Sunny
13       7.4         17.9      69.0         6.5             Rainy
14      14.9         15.1      81.0         8.7             Rainy
15      19.2         16.8      77.0         7.2             Rainy
16       5.6         18.5      63.0         4.9             Rainy
17       0.0         21.2      51.0         3.3             Sunny
18      10.8         17.6      75.0         6.7             Rainy
19      16.3         14.5      84.0         9.1             Rainy
20       3.9         16.1      71.0         5.3             Rainy
21       0.0         19.4      59.0         4.1             Sunny
22       7.1         18.2      67.0         7.1             Rainy
23      12.7         15.7      79.0         8.3             Rainy
24      18.4         17.1      76.0         6.8             Rainy
25       9.8         19.7      62.0         4.7             Rainy
26       0.0         22.9      47.0         2.5             Sunny
27       6.2         18.5      70.0         7.3             Rainy
28      15.5         14.2      83.0         9.5             Rainy
29      21.8         16.4      78.0         7.6             Rainy
30      11.6         19.1      65.0         5.1             Rainy
31       0.0         21.6      53.0         3.7             Sunny
32       4.3         17.2      73.0         7.5             Rainy
33       9.1         15.4      81.0         8.9             Rainy
34      17.9         16.7      77.0         6.2             Rainy
35       7.5         18.9      64.0         4.3             Rainy
36       0.0         22.1      49.0         2.7             Sunny
37       5.8         17.8      72.0         6.9             Rainy
38      13.2         14.7      85.0         9.3             Rainy
39      19.6         16.2      79.0         7.8             Rainy
40      10.4         19.5      66.0         5.5             Rainy
41       0.0         23.4      44.0         3.1             Sunny
42       6.7         18.1      74.0         7.7             Rainy
43      14.8         13.9      87.0         9.9             Rainy
44      20.5         15.6      81.0         8.2             Rainy
45       8.3         19.2      68.0         6.1             Rainy
46       0.0         22.7      51.0         4.5             Sunny
47       5.1         17.4      75.0         8.3             Rainy
48      11.9         14.1      89.0        10.5             Rainy
49      17.3         15.9      83.0         8.6             Rainy
50       9.6         18.6      71.0         6.7             Rainy
51       0.0         21.3      55.0         5.1             Sunny
52       7.4         16.8      77.0         8.9             Rainy

In [56]:
from sklearn.model_selection import train_test_split

In [57]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [58]:
x=ds[["rainfall","temperature","humidity","wind_speed"]]
y=ds[["weather_condition"]]

In [59]:
r=BernoulliNB()

In [60]:
r.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

BernoulliNB()

In [65]:
check=[[0.0,19.4,59.0,4.1]]
pr=r.predict(check)
pr
print("predicted new weather:",pr)

predicted new weather: ['Sunny']

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but BernoulliNB was fitted with feature names
  warnings.warn(

In [66]:
ch=[[11.6,19.1,65.0,5.1]]
p=r.predict(ch)
p
print("predicted new weather:",p)

predicted new weather: ['Rainy']

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but BernoulliNB was fitted with feature names
  warnings.warn(