In [2]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

In [5]:
url="https://www.worldometers.info/world-population/"

In [7]:
response=requests.get(url)

In [9]:
soup=BeautifulSoup(response.text,"html.parser")

In [11]:
table=soup.find("table")
rows=table.find_all("tr")

In [12]:
data = []

for row in rows:
    columns = row.find_all(["td", "th"])
    columns = [c.text.strip() for c in columns]
    data.append(columns)

In [13]:
datas=pd.DataFrame(data[1:],columns=data[0])
datas

,Year (July 1),Population,Yearly % Change,Yearly Change,Median Age,Fertility Rate,Density (P/KmÂ²)
0,2026,"8,300,678,395",0.84%,"69,065,325",31.1,2.23,56
1,2025,"8,231,613,070",0.85%,"69,640,498",30.9,2.24,55
2,2024,"8,161,972,572",0.87%,"70,237,642",30.6,2.25,55
3,2023,"8,091,734,930",0.88%,"70,327,738",30.4,2.25,54
4,2022,"8,021,407,192",0.84%,"66,958,801",30.1,2.27,54
5,2021,"7,954,448,391",0.86%,"67,447,099",29.8,2.29,53
6,2020,"7,887,001,292",1.09%,"83,301,884",29.6,2.32,53
7,2015,"7,470,491,872",1.25%,"89,751,945",28.3,2.54,50
8,2010,"7,021,732,148",1.29%,"86,952,403",27.2,2.6,47
9,2005,"6,586,970,132",1.31%,"83,053,428",26.1,2.63,44
10,2000,"6,171,702,993",1.39%,"82,564,802",25.1,2.75,41
11,1995,"5,758,878,982",1.57%,"86,215,174",24,2.89,39
12,1990,"5,327,803,110",1.82%,"91,771,929",22.9,3.31,36
13,1985,"4,868,943,465",1.83%,"84,267,446",22,3.52,33
14,1980,"4,447,606,236",1.79%,"75,374,192",21.5,3.74,30
15,1975,"4,070,735,277",1.96%,"75,210,297",20.7,4.08,27
16,1970,"3,694,683,794",2.07%,"72,030,018",20.3,4.83,25
17,1965,"3,334,533,703",2.03%,"63,812,562",20.8,5.07,22
18,1960,"3,015,470,894",1.93%,"55,051,420",21.5,4.7,20
19,1955,"2,740,213,792",1.91%,"49,424,189",21.8,5,18

In [15]:
datas.to_csv("World Population.csv")

In [16]:
pd.read_csv("World Population.csv")

,Unnamed: 0,Year (July 1),Population,Yearly % Change,Yearly Change,Median Age,Fertility Rate,Density (P/KmÂ²)
0,0,2026,"8,300,678,395",0.84%,"69,065,325",31.1,2.23,56
1,1,2025,"8,231,613,070",0.85%,"69,640,498",30.9,2.24,55
2,2,2024,"8,161,972,572",0.87%,"70,237,642",30.6,2.25,55
3,3,2023,"8,091,734,930",0.88%,"70,327,738",30.4,2.25,54
4,4,2022,"8,021,407,192",0.84%,"66,958,801",30.1,2.27,54
5,5,2021,"7,954,448,391",0.86%,"67,447,099",29.8,2.29,53
6,6,2020,"7,887,001,292",1.09%,"83,301,884",29.6,2.32,53
7,7,2015,"7,470,491,872",1.25%,"89,751,945",28.3,2.54,50
8,8,2010,"7,021,732,148",1.29%,"86,952,403",27.2,2.60,47
9,9,2005,"6,586,970,132",1.31%,"83,053,428",26.1,2.63,44
10,10,2000,"6,171,702,993",1.39%,"82,564,802",25.1,2.75,41
11,11,1995,"5,758,878,982",1.57%,"86,215,174",24.0,2.89,39
12,12,1990,"5,327,803,110",1.82%,"91,771,929",22.9,3.31,36
13,13,1985,"4,868,943,465",1.83%,"84,267,446",22.0,3.52,33
14,14,1980,"4,447,606,236",1.79%,"75,374,192",21.5,3.74,30
15,15,1975,"4,070,735,277",1.96%,"75,210,297",20.7,4.08,27
16,16,1970,"3,694,683,794",2.07%,"72,030,018",20.3,4.83,25
17,17,1965,"3,334,533,703",2.03%,"63,812,562",20.8,5.07,22
18,18,1960,"3,015,470,894",1.93%,"55,051,420",21.5,4.70,20
19,19,1955,"2,740,213,792",1.91%,"49,424,189",21.8,5.00,18